### ISSUE TITLE
Parse upper case words

### ISSUE THREAD

**Issue by anronin** [appcues/exconstructor#6]
Hi! Very nice library but i've got problem. How can i use exconstructor if data structure is `map`, key type is `string` and key format is like `GlobalIPv6Address`?
For example, here what i get from docker remote api

```
%{"Command" => "string",
  "Created" => 1459328030, "HostConfig" => %{"NetworkMode" => "default"},
  "Id" => "string",
  "Image" => "string",
  "ImageID" => "sha256:string",
  "Labels" => %{"build-date" => "2015-12-23", "license" => "GPLv2",
    "name" => "CentOS Base Image", "vendor" => "CentOS", "string" => ""},
  "Names" => ["/boring_varahamihira"],
  "NetworkSettings" => %{"Networks" => %{"bridge" => %{"Aliases" => nil,
        "EndpointID" => "string",
        "Gateway" => "172.17.0.1", "GlobalIPv6Address" => "",
        "GlobalIPv6PrefixLen" => 0, "IPAMConfig" => nil,
        "IPAddress" => "172.17.0.2", "IPPrefixLen" => 16, "IPv6Gateway" => "",
        "Links" => nil, "MacAddress" => "02:42:ac:11:00:02",
        "NetworkID" => ""}}},
  "Ports" => [%{"IP" => "0.0.0.0", "PrivatePort" => 80, "PublicPort" => 80,
     "Type" => "tcp"}], "Status" => "Up 3 weeks"}
```

**Comment by weaktyper** [comment]
I have a similar issues as you.

I think that in addition to UpperCamelCase, other fields in this json map will not be parsed.... 
For example: 
`ImageID` --> `image_url`, `IPAddress` --> `ip_address`

Because they have Upper Case only for more than the first character. 

So that is another separate issue. I don't think your Pull request addresses this issue?

Issue Description: 

**Parse upper case words**

**Comment by anronin** [comment]
you're right, to better describe this i'll change issue name

**Comment by weaktyper** [comment]
sorry, I was a bit unclear... I think your original description was correct! 
I'm going to create another issue for what I am referring to now.

**Comment by anronin** [comment]
ok, but I just thought at first that the problem only in the first letter but now I see that the problem is much wider and I think that is not so easy to solve it seemed to me at first

**Comment by stephenmoloney** [comment]
anronin, is it okay if I add my changes on top of yours... ie.. If my pull requests includes the changes in your branch?

Reason is that otherwise my tests will conflict with yours. (fieldNine) Instead I would prefer to move straight to field ten.

see [here](https://github.com/appcues/exconstructor/compare/master...stephenmoloney:master)

**Comment by anronin** [comment]
no problem

**Comment by jessejanderson** [comment]
So... is this being fixed? I see several pull requests for the fix but they all seem to have been closed without being merged and the issue still exists.

**Comment by sitch** [comment]
Seems like PR is okay, can we get this merged in?

**Comment by stephenmoloney** [comment]
@Sitch
I ended up making my own repository to find a solution to this. 
Not sure if it's a good fit for what you are doing but you can find it [here](https://github.com/stephenmoloney/mapail/tree/master).
`{:mapail, github: "stephenmoloney/mapail", branch: "master"}`
I plan to publish it to hex but it needs a few changes for various reasons... hope to get it published over the next few months.
